spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hb-05-many-to-many?autoReconnect=true&useSSL=false
    username: "hans"
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181